apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Tools\Kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: payment-service
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Tools\Kompose\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: payment-service
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://root:password@payment-postgres:5436/mydb
            - name: RABBITMQ_URL
              value: amqp://user:password@rabbitmq:5672
          image: payment-service
          name: payment-service
          imagePullPolicy: Never
          ports:
            - containerPort: 3004
              protocol: TCP
      restartPolicy: Always
