apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Tools\Kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: auth-service
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Tools\Kompose\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: auth-service
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://root:password@auth-postgres:5433/mydb
            - name: RABBITMQ_URL
              value: amqp://user:password@rabbitmq:5672
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          image: cars_rental/auth-service
          name: auth-service
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
              protocol: TCP
      restartPolicy: Always
