apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Tools\Kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: auth-postgres
  name: auth-postgres
spec:
  ports:
    - name: "5433"
      port: 5433
      targetPort: 5432
  selector:
    io.kompose.service: auth-postgres
