apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Tools\Kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: payment-service
  name: payment-service
spec:
  ports:
    - name: "3004"
      port: 3004
      targetPort: 3004
  selector:
    io.kompose.service: payment-service
