apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Tools\Kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: cars-service
  name: cars-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cars-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Tools\Kompose\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: cars-service
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://root:password@cars-postgres:5434/mydb
            - name: GATEWAY_URL
              value: http://gateway:3000
            - name: RABBITMQ_URL
              value: amqp://user:password@rabbitmq:5672
          image: cars_rental/cars-service
          name: cars-service
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
              protocol: TCP
      restartPolicy: Always
