apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Tools\Kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: cars-postgres
  name: cars-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cars-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Tools\Kompose\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: cars-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: mydb
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: root
          image: postgres:17.4-alpine3.21
          name: cars-postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: cars-postgres-data
      restartPolicy: Always
      volumes:
        - name: cars-postgres-data
          persistentVolumeClaim:
            claimName: cars-postgres-data
